Sonata\CatalogBundle\Entity\OrderItems:
    type: entity
    table: OrderItems
    repositoryClass: Sonata\CatalogBundle\Entity\OrderItemsRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        quantity:
            type: integer
        price:
            type: decimal
        total:
            type: decimal
    manyToOne:
      product:
        targetEntity: Product
        inversedBy: orderitems
        joinColumn:
          name: product_id
          referencedColumnName: id
      orders:
        targetEntity: Orders
        joinColumn:
          name: order_id
          referencedColumnName: id
        cascade: [persist, remove]  
    lifecycleCallbacks:
        postPersist: [ uploads ]      
        prePersist: [ uploading ]
