Sonata\CatalogBundle\Entity\Product:
    type: entity
    table: Product
    repositoryClass: Sonata\CatalogBundle\Entity\ProductRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: 255
        description:
            type: string
            length: 255
        summary:
            type: string
            length: 255
        isActive:
            type: boolean
            column: is_active
        slug:
            type: string
            length: 255
        quantity:
            type: integer
        price:
            type: decimal
    manyToOne:                
         brand:
            targetEntity: Brand
            joinColumn:
                name: brand_id
                referencedColumnName: id
    manyToMany:
        category:
          targetEntity: Category
          inversedBy: product
          joinTable:
            name: product_category
            joinColumns:
              product_id:
                referencedColumnName: id
            inverseJoinColumns:
              category_id:
                referencedColumnName: id     
    OnetoMany:
       OrderItems:
            targetEntity: OrderItems
            mappedBy: product
            cascade: [persist, remove]                
    lifecycleCallbacks: {  }
