<?php

namespace Sonata\CatalogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OrderItemsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderItemsRepository extends EntityRepository
{
}
